/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ilkka' at '5/9/17 12:50 PM' with Gradle 2.8
 *
 * @author ilkka, @date 5/9/17 12:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
